[tool.poetry]
name = "pythonproject16"
version = "0.1.0"
description = "Проект с функциями маскировки данных"
authors = ["Ваше Имя <ваш.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.lint.dependencies]
flake8 = "^6.0.0"
black = "^23.9.0"
isort = "^5.12.0"
mypy = "^1.5.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
